/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./../components/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./../components/BaseCheckbox.vue')['default']
    BaseInput: typeof import('./../components/BaseInput.vue')['default']
    BaseRadioGroup: typeof import('./../components/BaseRadioGroup.vue')['default']
    BaseSelect: typeof import('./../components/BaseSelect.vue')['default']
    copy: typeof import('./../components/BaseInput copy.vue')['default']
  }
}
